---
title: "MAT 180 Project"
output: html_document
---

Benjamin Sionit
Peiyu Han
Ziyi Ma

```{r setup, include=TRUE}

library(plotly)
library(tidyverse)
library(ggpubr)
library(dplyr)
library(glmnet)
library(MASS)
library(caret)
library(class)
library(hrbrthemes)
library(viridis)
library(plotly)
library(countrycode)
library(rvest)
library(reshape2)
library(car)
library(lmtest)
library(broom)
library(rstatix)
library(rgl)
library(gtools)
library(RcppAlgos)
library(crossword.r)


url = "https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/PG/2006/04/1-10000"
url2 = "https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/PG/2006/04/10001-20000"
url3 = "https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/PG/2006/04/20001-30000"
url4 = "https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/PG/2006/04/30001-40000"

#these are the urls for the Gutenberg Frequency Lists 
ProjGuten <- read_html(url)
ProjGutenTables10k <- html_table(ProjGuten, header = TRUE)

```


```{r}
makefreqlist <- function(url){
  ProjGuten <- read_html(url)
  ProjGutenTables <- html_table(ProjGuten, header = TRUE)
  wordfreq <- data.frame()
  for(x in 1:length(ProjGutenTables)){
  wordfreq <- rbind(wordfreq,ProjGutenTables[[x]])
  }
  return(wordfreq)
}
#this compiles the frequency lists for GutenBerg


wordfreqgutenberg <- rbind(rbind(rbind(makefreqlist(url),makefreqlist(url2)),makefreqlist(url3)),makefreqlist(url4))
colnames(wordfreqgutenberg)[3] <- "count"


wordfreq300k <- read.csv("/Users/benjaminsionit/Downloads/unigram_freq.csv") #https://www.kaggle.com/datasets/rtatman/english-word-frequency 333k Freqlist
wordfreqfinal <- wordfreqgutenberg
wordfreqfinal$count <- wordfreqfinal$count/sum(wordfreqfinal$count) 

colnames(wordfreqfinal)[3] <- "freq"
colnames(wordfreqfinal)[2] <- "word"


-1*sum(wordfreqfinal$freq*log2(wordfreqfinal$freq)) #Entropy of all 40k words in Guternberg list
wordfreqfinal <- wordfreqfinal[str_length(wordfreqfinal$word) > 2,]
wordfreqfinal <- wordfreqfinal[str_length(wordfreqfinal$word) < 6,] #gets all words in GutenBerg List lengths 3,4,5
wordfreqfinal$freq <- wordfreqfinal$freq/sum(wordfreqfinal$freq)#normalize freq again
-1*sum(wordfreqfinal$freq*log2(wordfreqfinal$freq)) #entropy of Gutenberg 40k given length3,4,or 5

setdiff(wordfreqfinal$word,wordfreq300k$word) #cross ref words in Gutenberg w/ caggle list, shows it does not contain proper nouns, etc 

wordfreqfinal <- wordfreqfinal[which(wordfreqfinal$word %in% wordfreq300k$word),] #get only words in Gutenberg list given it is in Kaggle 333k List 
wordfreqfinal$freq <- wordfreqfinal$freq/sum(wordfreqfinal$freq) #normalize freq again
-1*sum(wordfreqfinal$freq*log2(wordfreqfinal$freq)) #new entropy
```

```{r}

FiveChar = c('g','c','a','i','r') #letters in the circle
  


FindWords <- function(FiveChar){
wordlist <- data.frame()
for (n in 1:length(FiveChar)) {
  example <- data.frame()
for (x in 1:length(permuteGeneral(FiveChar,n)[,1])) {
  example <- rbind(example,gsub(" ", "",paste(permuteGeneral(FiveChar,n)[x,],"", collapse = "")))
  
}
  colnames(example)[1] <- 'anagram'
  wordlist <- rbind(wordlist,example)
}
colnames(example)[1] <- 'anagram'


RealWords <- wordfreqfinal[which(wordfreqfinal$word %in% wordlist$anagram),]
RealWords$freq <- RealWords$freq/sum(RealWords$freq)
RealWords <- RealWords[,-1]
return(RealWords)


}

#gets all real words from the anagrams of the FiveChar 


RealWords <- FindWords(FiveChar)
RealWords 


-1*sum(RealWords$freq*log2(RealWords$freq))#entropy of all words in Gutenberg given they are length 3,4,5, given they are also on the Kaggle List, given that they are only made out of the 5 letters in FiveChar


givenlength <- function(n){
  GivenLengthTable <- RealWords[str_length(RealWords$word) == n,]
  GivenLengthTable$freq <- GivenLengthTable$freq/sum(GivenLengthTable$freq)
  print(-1*sum(GivenLengthTable$freq*log2(GivenLengthTable$freq)))
  return(GivenLengthTable)
} #gives the list in RealWords (all words in Gutenberg given they are length 3,4,5, given they are also on the Kaggle List, given that they are only made out of the 5 letters in FiveChar) given they are length n, normalizes, calculates entropy with givens 

givenlength(3) 
```


```{r}
MakeCrossWord <- function(col){
  CrossWord <- matrix(nrow = length(col), ncol = nchar(col)[1])
  BarrierStrRow <- character(0)
  BarrierStrCol <- character(0)
  for (x in 1:length(col)) {
    Places <- which(strsplit(col[x],"")[[1]] == "_")
    Null <- which(strsplit(col[x],"")[[1]] == "#")
    CrossWord[x,Places] = "_"
    CrossWord[x,Null] = "#"
  }
  CrossWordWithBorders <- matrix(nrow = length(col)+2, ncol = nchar(col)[1]+2)
   for (x in 1:(length(col)+2)) {
    CrossWordWithBorders[x,] = "&"
   }
  for(x in 1:length(col)){
    for(y in 1:nchar(col)[[1]]){
      CrossWordWithBorders[x+1,y+1] <- CrossWord[x,y]
    }
  }
  return(CrossWordWithBorders)
} #makes crossword, imput in app, explained in doccument 

CrossWord <- MakeCrossWord(c("___##","##_##","_____","####_","___#_")) #example explained in doccument, level 59

CrossWord
```

```{r}
FindNodes <- function(matrix){
  AdjacencyMatrix <- matrix(nrow = dim(matrix)[[1]],ncol = dim(matrix)[[2]])
  for (x in 1:dim(AdjacencyMatrix)[[1]]) {
    AdjacencyMatrix[x,] = 0
  }
  for (x in 1:dim(matrix)[[1]]){
    for(y in 1:dim(matrix)[[2]]){
      if(matrix[x,y] == "_"){
        if(matrix[x-1,y] == "_" & matrix[x,y-1] == "_" ){
          AdjacencyMatrix[x,y] = AdjacencyMatrix[x,y] + 1
        }
        if(matrix[x-1,y] == "_" & matrix[x,y+1] == "_" ){
          AdjacencyMatrix[x,y] = AdjacencyMatrix[x,y] + 1
        }
        if(matrix[x+1,y] == "_" & matrix[x,y-1] == "_" ){
          AdjacencyMatrix[x,y] = AdjacencyMatrix[x,y] + 1
        }
        if(matrix[x+1,y] == "_" & matrix[x,y+1] == "_" ){
          AdjacencyMatrix[x,y] = AdjacencyMatrix[x,y] + 1
        }
      }  
    }
  }
  return(AdjacencyMatrix)
} #explained in doccument, gets Adj matrix with adjacenty defined in doccument (special type of connectionn)

GetMaximizedAdj <- function(AdjMatrix){
  MaxAdj <- data.frame()
  for (x in 1:dim(AdjMatrix)[[1]]) {
    for (y in 1:dim(AdjMatrix)[[2]]) {
    TotalSum <- sum(AdjMatrix[x,])+ sum(AdjMatrix[,y]) + AdjMatrix[x,y]
   MaxAdj <- rbind(MaxAdj,c(x,y,TotalSum))
  }
  }
 return(MaxAdj[which.max(MaxAdj[,3]),1:2]-1)
} #weighs adj matrix by column, row, and coordinate pair, gets max of the sum of their values, the largest word that contains that coordinate pair is in our definition, best place to start

AdjMatrix <- FindNodes(CrossWord)
AdjMatrix
GetMaximizedAdj(AdjMatrix)
```


```{r}
givenlength(5) #best place to start in our example was (3,3), word length 5 across 
```